<?php

declare(strict_types=1);

const OG_IMAGE_WIDTH = 1200;
const OG_IMAGE_HEIGHT = 630;

function media_favicon_initial(): string
{
    $title = trim((string) WIKI_TITLE);
    if ($title === '') {
        return 'W';
    }

    $initial = function_exists('mb_substr')
        ? (string) mb_substr($title, 0, 1)
        : substr($title, 0, 1);
    $initial = trim($initial);

    return $initial !== '' ? $initial : 'W';
}

function media_favicon_svg_markup(): string
{
    $initial = htmlspecialchars(media_favicon_initial(), ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $label = htmlspecialchars((string) WIKI_TITLE, ENT_QUOTES | ENT_HTML5, 'UTF-8');

    return implode('', [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="', $label, '">',
        '<text x="50%" y="50%" text-anchor="middle" dominant-baseline="central" fill="black" font-size="48" font-weight="700" ',
        'font-family="system-ui,-apple-system,Segoe UI,Roboto,sans-serif">', $initial, '</text>',
        '</svg>',
    ]);
}

function media_og_image_fallback_png(): string
{
    $fallback = base64_decode(
        'iVBORw0KGgoAAAANSUhEUgAABLAAAAJ2CAYAAABPQHtcAAARUklEQVR42u3YMQEAAAyDsPo3vdngSCRwsgMAAACAsEkAAAAAQJmBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAECagQUAAABAmoEFAAAAQJqBBQAAAEDaA9ykDRh59WSDAAAAAElFTkSuQmCC',
        true,
    );
    return is_string($fallback) ? $fallback : '';
}

function handle_favicon_svg(string $method, array $matches): void
{
    require_get_method($method);
    header('Content-Type: image/svg+xml; charset=utf-8');
    header('Cache-Control: public, max-age=3600');
    $etag = '"' . substr(hash('sha256', (string) WIKI_TITLE), 0, 24) . '"';
    header('ETag: ' . $etag);
    if (trim((string) ($_SERVER['HTTP_IF_NONE_MATCH'] ?? '')) === $etag) {
        http_response_code(304);
        return;
    }

    echo media_favicon_svg_markup();
}

function handle_og_image_png(string $method, array $matches): void
{
    require_get_method($method);

    header('Content-Type: image/png');
    echo media_og_image_fallback_png();
}
